# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-reason-app:
    docker:
      - image: circleci/node:8.13.0-stretch

    working_directory: ~/rememberme-front

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-main-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-main-dependencies-
      - run:
            name: Install dependencies
            command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-main-dependencies-{{ checksum "package.json" }}
      - run:
            name: Build
            command: |
              npm run build
              npm run webpack:production
      - persist_to_workspace: # Persist the specified paths (workspace/echo-output)
      # into the workspace  for use in downstream job. Must be an absolute path,
      # or relative path from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
          root: .
            # Must be relative path from root
          paths:
            - build
  push-build-and-firebase-items:
    docker:
      - image: circleci/node:8.13.0-stretch

    working_directory: ~/rememberme-front

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-main-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-main-dependencies-
      - run:
            name: Install Firebase
            command: npm install --save-dev firebase-tools
      - save_cache:
          paths:
            - node_modules
          key: v1-main-dependencies-{{ checksum "package.json" }}

      - attach_workspace:
          at: .
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  version: 2
  build-deploy-flow:
    jobs:
      - build-reason-app:
          filters:
            branches:
              only:
                - production
      - push-build-and-firebase-items:
          requires:
            - build-reason-app
          filters:
            branches:
              only:
                - production
